---
- hosts: all
  become: true
  vars:
    username: user2
  tasks:
    - name: Userdel
      user:
        name: "{{username}}"
        state: absent
    - name: Del homedir
      file:
        path: "/home/{{username}}"
        state: absent
